/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entities.Endereco;
import entities.Imovel;

/**
 *
 * @author arch
 */
public class ImovelForm extends javax.swing.JDialog {

    /**
     * Creates new form Imoveis
     */
    public ImovelForm(java.awt.Frame parent, Imovel imovel) {
        super(parent, true);
        
        this.imovel = imovel;
        initComponents();
        
        if(imovel.isValid()){
            setFields();
            cadastrarButton.setText("Salvar");            
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ocupadoGroup = new javax.swing.ButtonGroup();
        cadastrarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        imovelPanel = new javax.swing.JPanel();
        tipoLabel = new javax.swing.JLabel();
        tamanhoLabel = new javax.swing.JLabel();
        valorLabel = new javax.swing.JLabel();
        ocupadoLabel = new javax.swing.JLabel();
        financiamentoLabel = new javax.swing.JLabel();
        descricaoLabel = new javax.swing.JLabel();
        tipoCombo = new javax.swing.JComboBox<>();
        tamanhoText = new javax.swing.JTextField();
        valorText = new javax.swing.JTextField();
        simRadio = new javax.swing.JRadioButton();
        naoRadio = new javax.swing.JRadioButton();
        financiamentoCombo = new javax.swing.JComboBox<>();
        descricaoText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cadastrarButton.setText("Cadastrar Imovel");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        imovelPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IMOVEL", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        tipoLabel.setText("Tipo");

        tamanhoLabel.setText("Tamanho (m²)");

        valorLabel.setText("Valor");
        valorLabel.setToolTipText("Valor");

        ocupadoLabel.setText("Ocupado?");

        financiamentoLabel.setText("Financiamento");

        descricaoLabel.setText("Descricao");

        tipoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Casa", "Apartamento", "Terreno", "Ponto Comercial" }));
        tipoCombo.setToolTipText("");

        valorText.setToolTipText("Valor");

        ocupadoGroup.add(simRadio);
        simRadio.setText("Sim");
        simRadio.setToolTipText("Ocupado");

        ocupadoGroup.add(naoRadio);
        naoRadio.setText("Nao");
        naoRadio.setToolTipText("Desocupado");

        financiamentoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Proprio", "Bancario" }));

        javax.swing.GroupLayout imovelPanelLayout = new javax.swing.GroupLayout(imovelPanel);
        imovelPanel.setLayout(imovelPanelLayout);
        imovelPanelLayout.setHorizontalGroup(
            imovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imovelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descricaoLabel)
                    .addComponent(tipoLabel)
                    .addComponent(ocupadoLabel)
                    .addComponent(financiamentoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valorLabel)
                    .addComponent(tamanhoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imovelPanelLayout.createSequentialGroup()
                        .addComponent(tipoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(172, 172, 172))
                    .addComponent(descricaoText, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(imovelPanelLayout.createSequentialGroup()
                        .addComponent(simRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(naoRadio))
                    .addComponent(financiamentoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(imovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tamanhoText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addComponent(valorText, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(32, 32, 32))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        imovelPanelLayout.setVerticalGroup(
            imovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imovelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoLabel)
                    .addComponent(tipoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(imovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamanhoLabel)
                    .addComponent(tamanhoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(imovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorLabel)
                    .addComponent(valorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(imovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ocupadoLabel)
                    .addGroup(imovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(simRadio)
                        .addComponent(naoRadio)))
                .addGap(18, 18, 18)
                .addGroup(imovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(financiamentoLabel)
                    .addComponent(financiamentoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(imovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaoLabel)
                    .addComponent(descricaoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadastrarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imovelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(imovelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarButton)
                    .addComponent(cancelarButton))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        imovel = null;
        //this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        imovel.setTipo(tipoCombo.getSelectedItem().toString());
        imovel.setTamanho(Double.valueOf(tamanhoText.getText()));
        imovel.setValor(Double.valueOf(valorText.getText()));
        
        if(simRadio.isSelected()){
            imovel.setOcupado(true);
        }else if(naoRadio.isSelected()){
            imovel.setOcupado(false);
        }
        
        imovel.setFinanciamento(financiamentoCombo.getSelectedItem().toString());        
        imovel.setDescricao(descricaoText.getText());
        
        Endereco loc = new Endereco();
        /*
        loc.setTipoLogradouro(tipoLogrCombo.getSelectedItem().toString());
        loc.setNomeLogradouro(logrText.getText());
        loc.setNumero(Integer.valueOf(numeroText.getText()));
        loc.setBairro(bairroText.getText());
        loc.setCep(Integer.parseInt(cepText.getText()));
        loc.setComplemento(complemText.getText());
        loc.setCidade(cidadeText.getText());
        loc.setEstado(estadoCombo.getSelectedItem().toString());
        imovel.setLocalizacao(loc);*/
        
        this.dispose();
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setFields(){
        tipoCombo.setSelectedItem(imovel.getTipo());        
        tamanhoText.setText(String.valueOf(imovel.getTamanho()));        
        valorText.setText(String.valueOf(imovel.getValor()));
        if(imovel.getOcupado() != null && imovel.getOcupado()){
            simRadio.setSelected(true);
        }else{
            naoRadio.setSelected(true);
        }
        
        financiamentoCombo.setSelectedItem(imovel.getFinanciamento());              
        descricaoText.setText(imovel.getDescricao());
        
        //Endereco loc = imovel.getLocalizacao();
        /*tipoLogrCombo.setSelectedItem(loc.getTipoLogradouro());
        logrText.setText(loc.getNomeLogradouro());
        numeroText.setText(String.valueOf(loc.getNumero()));
        bairroText.setText(loc.getBairro());
        cepText.setText(String.valueOf(loc.getCep()));
        complemText.setText(loc.getComplemento());
        cidadeText.setText(loc.getCidade());
        estadoCombo.setSelectedItem(loc.getEstado()); */        
    }
    
    public void setEditable(boolean b){
        cadastrarButton.setEnabled(b);
        tipoCombo.setEnabled(b);
        
        tamanhoText.setEditable(b);
        tamanhoText.setEnabled(b);
        
        valorText.setEditable(b);
        valorText.setEnabled(b);
        
        simRadio.setEnabled(b);
        naoRadio.setEnabled(b);        
        
        financiamentoCombo.setEnabled(b);
        descricaoText.setEnabled(b);
                
        /*tipoLogrCombo.setEnabled(b);
        logrText.setEnabled(b);
        numeroText.setEnabled(b);
        bairroText.setEnabled(b);
        cepText.setEnabled(b);
        complemText.setEnabled(b);
        cidadeText.setEnabled(b);
        estadoCombo.setEnabled(b);*/
    }
    
    public Imovel getImovel(){
        return this.imovel;
    }
        
    private Imovel imovel;  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JTextField descricaoText;
    private javax.swing.JComboBox<String> financiamentoCombo;
    private javax.swing.JLabel financiamentoLabel;
    private javax.swing.JPanel imovelPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton naoRadio;
    private javax.swing.ButtonGroup ocupadoGroup;
    private javax.swing.JLabel ocupadoLabel;
    private javax.swing.JRadioButton simRadio;
    private javax.swing.JLabel tamanhoLabel;
    private javax.swing.JTextField tamanhoText;
    private javax.swing.JComboBox<String> tipoCombo;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JLabel valorLabel;
    private javax.swing.JTextField valorText;
    // End of variables declaration//GEN-END:variables
}
